services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  php:
    build: ./
    volumes:
      - ./:/var/www/html
    networks:
      - app_network

  mysqldb:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: appdb
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
    volumes:
      - data:/var/lib/mysql
    networks:
      - app_network
    ports:
      - "3306"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - "8081:80"
    networks:
      - app_network

volumes:
  data:

networks:
  app_network:
    driver: bridge
