services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  php:
    build: .
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.2
    environment:
      # 🚨 Changer si vous utilisez cette configuration en production
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: appdb
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - "8081:80"

volumes:
  data: