# #opcache.ini
# opcache.enable=1


# opcache.interned_strings_buffer=8
# opcache.fast_shutdown=1

# ; Empêche la mise en cache des fichiers qui ont été récemment modifiés
# ;Environnement spécifique :
# ;Pour la production, désactivez la vérification des timestamps pour des performances maximales :
# ;opcache.validate_timestamps=0
# ;opcache.revalidate_freq=0
# ;Pour le développement, utilisez :
# ;opcache.validate_timestamps=1
# ;opcache.revalidate_freq=2
# opcache.validate_timestamps=1 
# opcache.revalidate_freq=2

# opcache.max_accelerated_files=20000
# opcache.memory_consumption=256



# ; Active le préchargement des fichiers PHP si vous utilisez PHP >= 7.4
# ; Adapté aux frameworks comme Symfony ou Laravel
# opcache.preload=/path/to/preload.php
# opcache.preload_user=www-data

# ; Limite les journaux générés par OPCache
# opcache.log_verbosity_level=1

# ; Active la protection mémoire (utile en environnement multi-utilisateur)
# opcache.protect_memory=1

; Active OPCache
opcache.enable=1

; Taille de la mémoire partagée allouée à OPCache
opcache.memory_consumption=256

; Taille du buffer pour les chaînes internes
opcache.interned_strings_buffer=8

; Nombre maximum de fichiers PHP mis en cache
opcache.max_accelerated_files=20000

; Valide les fichiers modifiés toutes les 2 secondes (idéal pour le développement)
opcache.validate_timestamps=1
opcache.revalidate_freq=2

; Préchargement (assurez-vous que le fichier preload.php existe)
opcache.preload=/var/www/html/config/preload.php
opcache.preload_user=www-data

; Active une fermeture rapide
opcache.fast_shutdown=1

; Active la protection mémoire (utile en environnement multi-utilisateur)
opcache.protect_memory=1

; Limite les logs générés par OPCache
opcache.log_verbosity_level=1
