# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout

app_employe_login:
    path: /employe/login
    controller: App\Controller\EmployeSecurityController::login

app_admin_dashboard:
    path: /admin/dashboard
    controller: App\Controller\AdminController::dashboard

app_veterinaire_dashboard:
    path: /veterinaire/dashboard
    controller: App\Controller\VeterinaireController::dashboard

app_employe_dashboard:
    path: /employe/dashboard
    controller: App\Controller\EmployeController::dashboard

habitat_new:
    path: /habitat/new
    controller: App\Controller\HabitatController::new
    methods: [GET, POST]

habitat_index:
    path: /habitat
    controller: App\Controller\HabitatController::index

animal_index:
    path: /admin_animal
    controller: App\Controller\AdminAnimalController::index

animal_new:
    path: /admin_animal/create
    controller: App\Controller\AdminAnimalController::create
    methods: [GET, POST]

animal_edit:
    path: /admin_animal/edit/{id}
    controller: App\Controller\AdminAnimalController::edit
    methods: [GET, POST]

animal_delete:
    path: /admin_animal/delete/{id}
    controller: App\Controller\AdminAnimalController::delete
    methods: [POST]

contact:
    path: /contact
    controller: App\Controller\ContactController::index

about:
    path: /about
    controller: App\Controller\AboutController::index

admin_list_user:
    path: /admin/user/list_users
    controller: App\Controller\AdminController::listUsers

admin_create_user:
    path: /admin/user/create
    controller: App\Controller\AdminController::createUser

admin_edit_user:
    path: /admin/user/edit/{id}
    controller: App\Controller\AdminController::editUser

admin_delete_user:
    path: /admin/user/delete/{id}
    controller: App\Controller\AdminController::deleteUser

animal_crud:
    path: /admin_animal/{action}/{id}
    controller: App\Controller\AdminAnimalController::{action}
    methods: [GET, POST]
    requirements:
        action: create|edit|delete


avis_index:
    path: /avis
    controller: App\Controller\AvisController::index

avis_new:
    path: /avis/new
    controller: App\Controller\AvisController::new

avis_edit:
    path: /avis/edit/{id}
    controller: App\Controller\AvisController::edit

avis_delete:
    path: /avis/delete/{id}
    controller: App\Controller\AvisController::delete
    methods: [POST]

consultation_index:
    path: /consultations
    controller: App\Controller\ConsultationController::index

consultation_new:
    path: /consultations/new
    controller: App\Controller\ConsultationController::new

consultation_edit:
    path: /consultations/edit/{id}
    controller: App\Controller\ConsultationController::edit

consultation_delete:
    path: /consultations/delete/{id}
    controller: App\Controller\ConsultationController::delete
    methods: [POST]
