services:
    Symfony\Component\HttpFoundation\Session\SessionInterface: '@session'
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services en tant que commandes, abonnés aux événements, etc.

    # Rend les classes dans src/ disponibles pour être utilisées en tant que services
    # Cela crée un service par classe dont l'identifiant est le nom de classe entièrement qualifié
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/{Entity,Migrations,Tests}'
            - '../src/Kernel.php'

    App\Security\AuthAuthenticator:
    arguments:
        $urlGenerator: '@router'
        $requestStack: '@request_stack'
        $csrfTokenManager: '@security.csrf.token_manager'
    tags:
        - { name: 'security.authenticator' }


    # Définir un alias pour UserPasswordHasherInterface
    Symfony\Component\Security\Core\PasswordHasher\UserPasswordHasherInterface:
        alias: Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface
